name: Trivy Scan Job

on:
  workflow_call:

permissions:
  contents: read

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh
          echo "$(pwd)/bin" >> $GITHUB_PATH

      - name: Run Trivy vulnerability scan and generate report
        run: trivy fs --exit-code 1 --severity HIGH,CRITICAL .
